---
kind: Service
apiVersion: v1
metadata:
  name: $(DASHBOARD_NAME)
spec:
  selector:
    deployment: $(DASHBOARD_NAME)
  ports:
  - name: http
    protocol: TCP
    targetPort: 8080
    port: 8080
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  annotations:
  name: jupyterhub
  labels:
    app: jupyterhub
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
spec:
  ports:
    - name: 9080-tcp
      protocol: TCP
      port: 9080
      targetPort: 8080
    - name: 8081-tcp
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: jupyterhub
    component.opendatahub.io/name: jupyterhub
    deploymentconfig: jupyterhub
    opendatahub.io/component: 'true'
  type: ClusterIP
  sessionAffinity: None
